### PR TITLE
Sprint 1 reupload

### PR DESCRIPTION
**Pull request by omarhassaneg**

### CODE REVIEW

**Comment by ghost** [comment]
[Sprint 1.pdf](https://github.com/terratenney/CSDA-1050F18S1/files/3474464/Sprint.1.pdf)

**Comment by Semion78** [comment]
[Semion Gengrinovich-CSDA1050 sprint 1.pdf](https://github.com/terratenney/CSDA-1050F18S1/files/3474874/Semion.Gengrinovich-CSDA1050.sprint.1.pdf)

**Comment by omarhassaneg** [comment]
Sprint 2 Update

**Comment by omarhassaneg** [comment]
Sprint 2 update

**Pull request closed without merging**
